### ISSUE TITLE
Assistance with Image Time Points in Embryo Dataset

### ISSUE THREAD

**Issue by Reemann** [mueller-lab/TwinNet#1]
Dear Authors,

Thank you for sharing the valuable embryo image dataset. I am reaching out to seek clarification on the exact imaging time points for the images in the dataset downloaded from `https://dx.doi.org/10.48606/50`.

While the sub-dataset descriptions provide general start and end times, as well as intervals, I am looking for precise timing details for each image. Could you please guide me on where to find this information or how to determine the specific time points?

Your assistance is greatly appreciated.

Best regards,
Reemann

**Comment by mueller-lab** [comment]
The specific time points can be determined as follows: t_n = t_0 + n*I, where t_0 (start time of imaging) and I (imaging interval) are given on KonData (https://dx.doi.org/10.48606/50). For example t_300 = 3.75 h + 300*I = 3.75 h + 300*((300 s * 1 h)/(60 s * 60)) = 28.75 h. For some data sets, a small range of t_0 is given due to uncertainties in egg laying or egg collection from multiple cages. If you need to resolve t_0 for individual embryos, please assess the number of cells as a robust measure of embryo age.
